/** Figma exercise video frame — keeps full body visible without black letterboxing. */
export const EXERCISE_VIDEO_FRAME_WIDTH = 349;
export const EXERCISE_VIDEO_FRAME_HEIGHT = 444;
export const EXERCISE_VIDEO_FRAME_ASPECT =
  EXERCISE_VIDEO_FRAME_WIDTH / EXERCISE_VIDEO_FRAME_HEIGHT;
export const EXERCISE_VIDEO_FRAME_BACKGROUND = '#FFFFFF';
export const EXERCISE_VIDEO_FRAME_BORDER_RADIUS = 16;

/** Compact home day-card preview — video ~40% of card height in Figma. */
export const HOME_DAY_CARD_PREVIEW_WIDTH = 321;
export const HOME_DAY_CARD_PREVIEW_HEIGHT = 200;
export const HOME_DAY_CARD_PREVIEW_ASPECT =
  HOME_DAY_CARD_PREVIEW_WIDTH / HOME_DAY_CARD_PREVIEW_HEIGHT;

/** Session list exercise card preview (Welcome to Day X screen). */
export const SESSION_EXERCISE_CARD_PREVIEW_WIDTH = 328;
export const SESSION_EXERCISE_CARD_PREVIEW_HEIGHT = 280;
export const SESSION_EXERCISE_CARD_PREVIEW_ASPECT =
  SESSION_EXERCISE_CARD_PREVIEW_WIDTH / SESSION_EXERCISE_CARD_PREVIEW_HEIGHT;
export const SESSION_EXERCISE_CARD_PREVIEW_BACKGROUND = '#FFFFFF';
