import { getSupabase } from './supabase';
import {
  CANCER_TYPE_SLUGS,
  cancerPathMatchesSlug,
  getPathwayStorageRoot,
  parseLevelFromStoragePath,
  type CancerTypeSlug,
  type PathwayProfile,
} from './cancerPathway';
import {
  getPathwayExerciseSequence,
  getPathwayLevelRepDefault,
  storageSlugMatchesProgramKey,
  type PathwayExerciseKey,
} from './cancerPathwayPrograms';
import { comparePathwayFiles, parsePathwayFilename } from './pathwayFilenameParser';
import { resolvePathwayExerciseCopy } from './pathwayExerciseContent';
import type { GuidedSessionExercise, SessionDisplayLabel, SessionRepType } from './getDay1Session';
import { getPublicVideoUrl } from './supabaseStorage';

const REST_SECONDS = 20;

let cachedPaths: string[] | null = null;
let loadPromise: Promise<string[]> | null = null;

type ParsedPathwayClip = {
  objectPath: string;
  fileMeta: ReturnType<typeof parsePathwayFilename>;
  copy: ReturnType<typeof resolvePathwayExerciseCopy>;
  publicUrl: string;
};

function loadBundledPathwayPaths(): string[] {
  try {
    // Optional offline fallback generated by scripts/generate-pathway-manifest.mjs
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const bundled = require('../data/pathway-videos.json') as {
      paths?: unknown;
    };
    if (!Array.isArray(bundled.paths)) return [];
    return bundled.paths.filter((entry): entry is string => typeof entry === 'string');
  } catch {
    return [];
  }
}

async function fetchPathwayPathsFromSupabase(): Promise<string[]> {
  const supabase = getSupabase();
  if (!supabase) return [];

  const { data, error } = await supabase.rpc('list_pathway_video_paths');
  if (error) {
    console.warn('[PathwayVideoIndex] RPC failed', error.message);
    return [];
  }
  if (!Array.isArray(data)) return [];
  return data.filter((entry): entry is string => typeof entry === 'string');
}

export async function ensurePathwayVideoPathsLoaded(): Promise<string[]> {
  if (cachedPaths) return cachedPaths;
  if (!loadPromise) {
    loadPromise = (async () => {
      const remote = await fetchPathwayPathsFromSupabase();
      if (remote.length > 0) {
        cachedPaths = remote;
        return remote;
      }
      const bundled = loadBundledPathwayPaths();
      if (bundled.length > 0) {
        console.warn(
          `[PathwayVideoIndex] Using bundled pathway manifest (${bundled.length} paths)`,
        );
      }
      cachedPaths = bundled;
      return bundled;
    })();
  }
  return loadPromise;
}

export function clearPathwayVideoCache(): void {
  cachedPaths = null;
  loadPromise = null;
}

function objectPathsForProfileLevel(
  paths: string[],
  profile: PathwayProfile,
  level: number,
): string[] {
  const root = getPathwayStorageRoot(profile.gender, profile.avatar, profile.language);
  const prefix = `${root}/`;

  return paths.filter((objectPath) => {
    if (!objectPath.startsWith(prefix)) return false;
    const segments = objectPath.split('/');
    const cancerFolder = segments[1] ?? '';
    if (!cancerPathMatchesSlug(cancerFolder, profile.cancerType)) return false;
    const parsedLevel = parseLevelFromStoragePath(objectPath);
    return parsedLevel === level;
  });
}

function parseClips(objectPaths: string[]): ParsedPathwayClip[] {
  return objectPaths.map((objectPath) => {
    const fileName = objectPath.split('/').pop() ?? objectPath;
    const fileMeta = parsePathwayFilename(fileName);
    const copy = resolvePathwayExerciseCopy(fileMeta.rawLabel);
    const publicUrl = getPublicVideoUrl(objectPath) ?? '';
    return { objectPath, fileMeta, copy, publicUrl };
  });
}

function sideRank(slug: string): number {
  if (slug.endsWith('-left')) return 0;
  if (slug.endsWith('-right')) return 1;
  return 2;
}

function sortClipsForStep(a: ParsedPathwayClip, b: ParsedPathwayClip): number {
  const side = sideRank(a.copy.slug) - sideRank(b.copy.slug);
  if (side !== 0) return side;
  return comparePathwayFiles(a.fileMeta, b.fileMeta);
}

function cancerSlugFromPath(objectPath: string): CancerTypeSlug | null {
  const folder = objectPath.split('/')[1] ?? '';
  for (const slug of CANCER_TYPE_SLUGS) {
    if (cancerPathMatchesSlug(folder, slug)) return slug;
  }
  return null;
}

/** One diagram step: the next numeric group, left before right. */
function takeProgramGroup(
  pool: ParsedPathwayClip[],
  step: PathwayExerciseKey,
): ParsedPathwayClip[] {
  const matches = pool
    .filter((clip) => storageSlugMatchesProgramKey(clip.copy.slug, step))
    .sort(sortClipsForStep);
  if (matches.length === 0) return [];

  const nextOrder = matches[0]!.fileMeta.sortOrder;
  const group = matches
    .filter((clip) => clip.fileMeta.sortOrder === nextOrder)
    .sort(sortClipsForStep);

  for (const match of group) {
    const index = pool.indexOf(match);
    if (index >= 0) pool.splice(index, 1);
  }
  return group;
}

/**
 * Order clips by the pathway table only.
 * A missing step can use the same exercise from another cancer folder
 * for this gender, language, and level. Storage extras (for example
 * Ankle Pumps inside Head & Neck) are left out.
 */
function orderClipsByPathwayProgram(
  clips: ParsedPathwayClip[],
  cancerType: PathwayProfile['cancerType'],
  level: number,
  fallbackClips: ParsedPathwayClip[] = [],
): ParsedPathwayClip[] {
  const program = getPathwayExerciseSequence(cancerType, level);
  if (program.length === 0) {
    return [...clips].sort((a, b) => comparePathwayFiles(a.fileMeta, b.fileMeta));
  }

  const remaining = [...clips];
  const fallback = [...fallbackClips];
  const ordered: ParsedPathwayClip[] = [];

  for (const step of program) {
    const local = takeProgramGroup(remaining, step);
    if (local.length > 0) {
      ordered.push(...local);
      continue;
    }

    for (const source of CANCER_TYPE_SLUGS) {
      if (source === cancerType) continue;
      const fromSource = fallback.filter(
        (clip) => cancerSlugFromPath(clip.objectPath) === source,
      );
      const borrowed = takeProgramGroup(fromSource, step);
      if (borrowed.length === 0) continue;
      for (const match of borrowed) {
        const index = fallback.findIndex((clip) => clip.objectPath === match.objectPath);
        if (index >= 0) fallback.splice(index, 1);
      }
      ordered.push(...borrowed);
      break;
    }
  }

  return ordered;
}

function applyLevelRepDefaults(
  clip: ParsedPathwayClip,
  level: number,
): {
  repType: SessionRepType;
  repValue: number;
  displayValue: string;
  displayLabel: SessionDisplayLabel;
} {
  // Spot marching / timed clips keep filename duration.
  if (clip.fileMeta.displayLabel === 'MINS' || clip.fileMeta.displayLabel === 'SECS') {
    return {
      repType: clip.fileMeta.repType,
      repValue: clip.fileMeta.repValue,
      displayValue: clip.fileMeta.displayValue,
      displayLabel: clip.fileMeta.displayLabel,
    };
  }

  // Prefer explicit rep count from filename when present.
  if (clip.fileMeta.displayLabel === 'REPS' && clip.fileMeta.repValue > 0) {
    return {
      repType: clip.fileMeta.repType,
      repValue: clip.fileMeta.repValue,
      displayValue: clip.fileMeta.displayValue,
      displayLabel: clip.fileMeta.displayLabel,
    };
  }

  const defaults = getPathwayLevelRepDefault(level);
  const padded = defaults.reps < 10 ? `0${defaults.reps}` : String(defaults.reps);
  return {
    repType: 'reps',
    repValue: defaults.reps,
    displayValue: padded,
    displayLabel: 'REPS',
  };
}

export function buildGuidedExercisesFromPaths(
  objectPaths: string[],
  level: number,
  profile: PathwayProfile,
  fallbackObjectPaths: string[] = [],
): GuidedSessionExercise[] {
  const clips = orderClipsByPathwayProgram(
    parseClips(objectPaths),
    profile.cancerType,
    level,
    parseClips(fallbackObjectPaths),
  );

  return clips.map((entry, index) => {
    const reps = applyLevelRepDefaults(entry, level);
    return {
      id: `pathway-${profile.cancerType}-L${level}-s${index}-${entry.copy.slug}`,
      title: entry.copy.title,
      description: entry.copy.description,
      storageObjectPath: entry.objectPath,
      videoUrl: entry.publicUrl,
      repType: reps.repType,
      repValue: reps.repValue,
      displayValue: reps.displayValue,
      displayLabel: reps.displayLabel,
      portraitVideo: entry.objectPath,
    };
  });
}

export async function getPathwaySessionExercises(
  profile: PathwayProfile,
  level: number,
): Promise<GuidedSessionExercise[]> {
  const paths = await ensurePathwayVideoPathsLoaded();
  const levelPaths = objectPathsForProfileLevel(paths, profile, level);
  const root = getPathwayStorageRoot(profile.gender, profile.avatar, profile.language);
  const prefix = `${root}/`;
  const fallbackPaths = paths.filter((objectPath) => {
    if (!objectPath.startsWith(prefix) || levelPaths.includes(objectPath)) return false;
    return parseLevelFromStoragePath(objectPath) === level;
  });
  return buildGuidedExercisesFromPaths(levelPaths, level, profile, fallbackPaths);
}

export function getPathwaySessionRestSeconds(): number {
  return REST_SECONDS;
}
