// Portrait placeholders from Supabase folder "Placeholders Oncomsart Phase 2".
// Paths are bucket-relative. Prefer Level 1 and skip "(1)" duplicates.

export const PHASE2_PLACEHOLDER_ROOT = 'Placeholders Oncomsart Phase 2';

export const PHASE2_MALE_PLACEHOLDERS: Partial<Record<string, string>> = {
  'ankle-pumps': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/2.Ankle Pumps With Cot Male English 5Reps.png",
  'arm-circles': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/4.Arm Circles male English 5Reps.png",
  'biceps-curls': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/5.Biceps Curls male English 5Reps.png",
  'calf-raise': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 2 - Abdomen Cancer - Male - English -/8.Calf Raise Male English 5Reps.png",
  'calf-stretch': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 2 - Abdomen Cancer - Male - English -/12.Calf Stretch Male Left English.png",
  'calf-stretch-left': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 2 - Abdomen Cancer - Male - English -/12.Calf Stretch Male Left English.png",
  'calf-stretch-right': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 2 - Abdomen Cancer - Male - English -/12.Calf Stretch Male Right English.png",
  'chest-stretch': "Placeholders Oncomsart Phase 2/Male - English/Breast Cancer - Male - English/Level 1 - Breast Cancer - Male - English -/4.Pectoralis Stretch Male New English.png",
  'diaphragmatic-breathing': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/1.Dbe New male Tamil 5Reps.png",
  'hamstring-stretch': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/8.Hamstring male With Cot English.png",
  'jaw-side-to-side': "Placeholders Oncomsart Phase 2/Male - English/Head and Neck Cancer - Male - English/Level 1 - Head and Neck Cancer - Male - English -/6. Jaw side-side male.png",
  'neck-stretch': "Placeholders Oncomsart Phase 2/Male - English/Head and Neck Cancer - Male - English/Level 1 - Head and Neck Cancer - Male - English -/7.Neck Stretch male Left English New.png",
  'neck-stretch-left': "Placeholders Oncomsart Phase 2/Male - English/Head and Neck Cancer - Male - English/Level 1 - Head and Neck Cancer - Male - English -/7.Neck Stretch male Left English New.png",
  'neck-stretch-right': "Placeholders Oncomsart Phase 2/Male - English/Head and Neck Cancer - Male - English/Level 1 - Head and Neck Cancer - Male - English -/7.Neck Stretch male right  English New.png",
  'quadriceps-stretch': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/9.Quadriceps Stretch left Male English.png",
  'quadriceps-stretch-left': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/9.Quadriceps Stretch left Male English.png",
  'quadriceps-stretch-right': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/9.Quadriceps Stretch right Male English.png",
  'seated-knee-extension': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/6.Knee Extension Male left English 5Reps.png",
  'seated-knee-extension-left': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/6.Knee Extension Male left English 5Reps.png",
  'seated-knee-extension-right': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/6.Knee Extension Male Right English 5Reps.png",
  'shoulder-shrugging': "Placeholders Oncomsart Phase 2/Male - English/Thoraxic Cancer - Male - English/Level 1 - Thoraxic Cancer - Male - English/5.Shoulder Shrugs Male English 5Reps.png",
  'spot-marching': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/11.Spot Marching male Tamil 1Min.png",
  'standing-hamstring-curls': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 2 - Abdomen Cancer - Male - English -/7.Hamstring Curls Male left English 5 Reps.png",
  'standing-hamstring-curls-left': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 2 - Abdomen Cancer - Male - English -/7.Hamstring Curls Male left English 5 Reps.png",
  'standing-hamstring-curls-right': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 2 - Abdomen Cancer - Male - English -/7.Hamstring Curls Male Right English 5 Reps.png",
  'straight-leg-raise': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/7.Slr Male Left English 5Reps.png",
  'straight-leg-raise-left': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/7.Slr Male Left English 5Reps.png",
  'straight-leg-raise-right': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/7.Slr Male Right English 5Reps.png",
  'thoracic-expansion': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/3.Tee Male English 5Reps.png",
  'triceps-stretch': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/10.Triceps stretch male left english new.png",
  'triceps-stretch-left': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/10.Triceps stretch male left english new.png",
  'triceps-stretch-right': "Placeholders Oncomsart Phase 2/Male - English/Abdomen Cancer - Male - English/Level 1 - Abdomen Cancer - Male - English -/10.Triceps stretch male right english new.png",
  'wall-climbing': "Placeholders Oncomsart Phase 2/Male - English/Breast Cancer - Male - English/Level 1 - Breast Cancer - Male - English -/7.Wall Climbing Male Left English 5Reps.png",
  'wall-climbing-left': "Placeholders Oncomsart Phase 2/Male - English/Breast Cancer - Male - English/Level 1 - Breast Cancer - Male - English -/7.Wall Climbing Male Left English 5Reps.png",
  'wall-climbing-right': "Placeholders Oncomsart Phase 2/Male - English/Breast Cancer - Male - English/Level 1 - Breast Cancer - Male - English -/7.Wall Climbing Male Right English 5Reps.png",
  'wall-pushup': "Placeholders Oncomsart Phase 2/Male - English/Breast Cancer - Male - English/Level 2 - Breast Cancer - Male - English -/10.Wall Pushup male Tamil 5Reps.png",
  'wall-slides': "Placeholders Oncomsart Phase 2/Male - English/Breast Cancer - Male - English/Level 2 - Breast Cancer - Male - English -/9.Wall Slide Male English 5Reps.png",
};

export const PHASE2_FEMALE_PLACEHOLDERS: Partial<Record<string, string>> = {
  'ankle-pumps': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/2.Ankle Pumps With Cot FeMale English 5Reps.png",
  'arm-circles': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/4.Arm Circles Female English 5Reps.png",
  'biceps-curls': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/5.Biceps Curls Female English 5Reps.png",
  'calf-raise': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 2 - Abdomen Cancer - Female - English -/8.Calf Raise FeMale English 5Reps.png",
  'calf-stretch': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 2 - Abdomen Cancer - Female - English -/12.Calf Stretch FeMale Left English.png",
  'calf-stretch-left': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 2 - Abdomen Cancer - Female - English -/12.Calf Stretch FeMale Left English.png",
  'calf-stretch-right': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 2 - Abdomen Cancer - Female - English -/12.Calf Stretch FeMale Right English.png",
  'chest-stretch': "Placeholders Oncomsart Phase 2/Female - English/Breast Cancer - Female - English/Level 1 - Breast Cancer - Female - English -/4.Chest Stretch FeMale New English.png",
  'diaphragmatic-breathing': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/1.Dbe New Female Tamil 5Reps.png",
  'hamstring-stretch': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/8.Hamstring Female With Cot English.png",
  'jaw-side-to-side': "Placeholders Oncomsart Phase 2/Female - English/Head and Neck Cancer - Female - English/Level 1 - Head and Neck Cancer - Female - English -/6. Jaw side-side female.png",
  'quadriceps-stretch': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/9.Quadriceps Stretch left FeMale English.png",
  'quadriceps-stretch-left': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/9.Quadriceps Stretch left FeMale English.png",
  'quadriceps-stretch-right': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/9.Quadriceps Stretch Right FeMale English.png",
  'seated-knee-extension': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/6.Knee Extension FeMale Left English 5Reps.png",
  'seated-knee-extension-left': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/6.Knee Extension FeMale Left English 5Reps.png",
  'seated-knee-extension-right': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/6.Knee Extension FeMale Right English 5Reps.png",
  'shoulder-shrugging': "Placeholders Oncomsart Phase 2/Female - English/Thoraxic Cancer - Male - English/Level 1 - Thoraxic Cancer - Female - English -/5.Shoulder Shrugs FeMale English 5Reps.png",
  'spot-marching': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/11.Spot Marching Female Tamil 1Min.png",
  'standing-hamstring-curls': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 2 - Abdomen Cancer - Female - English -/7.Hamstring Curls FeMale left English 5 Reps.png",
  'standing-hamstring-curls-left': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 2 - Abdomen Cancer - Female - English -/7.Hamstring Curls FeMale left English 5 Reps.png",
  'standing-hamstring-curls-right': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 2 - Abdomen Cancer - Female - English -/7.Hamstring Curls FeMale Right English 5 Reps.png",
  'straight-leg-raise': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/7.Slr FeMale Left English 5Reps.png",
  'straight-leg-raise-left': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/7.Slr FeMale Left English 5Reps.png",
  'straight-leg-raise-right': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/7.Slr FeMale Right English 5Reps.png",
  'thoracic-expansion': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/3.Tee FeMale English 5Reps.png",
  'triceps-stretch': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/10.Triceps stretch female left english new.png",
  'triceps-stretch-left': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/10.Triceps stretch female left english new.png",
  'triceps-stretch-right': "Placeholders Oncomsart Phase 2/Female - English/Abdomen Cancer - Female - English/Level 1 - Abdomen Cancer - Female - English -/10.Triceps stretch female right english new.png",
  'wall-climbing': "Placeholders Oncomsart Phase 2/Female - English/Breast Cancer - Female - English/Level 1 - Breast Cancer - Female - English -/7.Wall Climbing FeMale Left English 5Reps.png",
  'wall-climbing-left': "Placeholders Oncomsart Phase 2/Female - English/Breast Cancer - Female - English/Level 1 - Breast Cancer - Female - English -/7.Wall Climbing FeMale Left English 5Reps.png",
  'wall-climbing-right': "Placeholders Oncomsart Phase 2/Female - English/Breast Cancer - Female - English/Level 1 - Breast Cancer - Female - English -/7.Wall Climbing FeMale Right English 5Reps.png",
  'wall-pushup': "Placeholders Oncomsart Phase 2/Female - English/Breast Cancer - Female - English/Level 2 - Breast Cancer - Female - English -/10.Wall Pushup Female Tamil 5Reps.png",
  'wall-slides': "Placeholders Oncomsart Phase 2/Female - English/Breast Cancer - Female - English/Level 2 - Breast Cancer - Female - English -/9.Wall Slide FeMale English 5Reps.png",
};
